### ISSUE TITLE
Dual-license under MIT

### ISSUE THREAD

**Issue by DemiMarie** [ezrosent/allocators-rs#63]
Would it be possible to dual-license under the MIT license?  This would allow use in the Rust compiler distribution and the Redox operating system.

**Comment by joshlf** [comment]
Per the discussion [here](https://users.rust-lang.org/t/announcing-elfmalloc-a-pure-rust-allocator-thats-competitive-on-performance-with-jemalloc/12693/8), @ezrosent and I have decided to dual-license.

Since contributors retain copyright, we need the permission of each of our contributors to retroactively release their contributions under an MIT license. @ezrosent , @Dr-Emann , and @adrian5 , please comment here stating whether or not you're OK with releasing your existing contributions under a dual Apache-2.0/MIT license.

**Comment by Dr-Emann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I license past and future contributions to allocators-rs under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJZuCpECRBe2Vi1fxtaxgAA6PcQAG4USKyU9EBRebwAu9mviGNr
mpfjFHN4hOtoXE9w1KPeQIRSSjqogwUXA4Vb7wFzhRyAvPU94oIAT1xDoN36o/OU
QnQCuGyg1xnjDmuH52qhy21xOmz+V5EWu1k5Dl/MzOHJEv+Tm2rDxvAtNQQ4BlW8
w2aRg4bFdgWvMatCME/m5q+wE//rEPVtnJ0GivbQUSCT3Jq2Scc95hRfMkATSJhq
455610c4TGgQ1lBkbS7b4FIQkUdsZ95wb+0/IfkdHN2kTj4Br2/QBUvc+7zz0FXD
oPq964eVBXY0ujPp0KEpf33UdsficRBWimpwSwV1QP6VqW1GIQHANP6wbpkpOoNQ
5A49onY4V/rPJ4WW8cla8o34hgtoCyAoIQcFklvHeBhMtyvEGWUrOPRBKGMNVzuy
k2FUO5WKiM9wD7LCWxcQx4hv9PBCphvdaHLOS7u0+5wQfg9+jp1I2XiojJOv+qOl
FCoDPW3SKyYRnHCQ8DMwQF6yJefO8Fgmb1oT4Zeqz4cAZHiE+zZNK3f2IeUSQD/f
NP6gnZ0Zi/qEckV0B+ufPekxsAWMAKfNrn0Ldnz6+kMLbQ6+nmgW4lMLXXJBUEjs
4eR7d9mLFAci+rEoUfgVBhHx0+0ZZQArWLU1YLqOBVhw2P4vKoKELcqyIqi6TBBj
nzjtlcwq44SqOdHLGiXp
=Uosb
-----END PGP SIGNATURE-----

**Comment by ezrosent** [comment]
I grant permission for my past and future contributions to be licensed under the dual MIT/Apache-2.0 license.

**Comment by adrian5** [comment]
I grant permission for my past and future contributions to be licensed under the dual MIT/Apache-2.0 license.

**Comment by joshlf** [comment]
Awesome, thanks folks! We're now dual licensed!
